name: SwipeFresh
settings:
  DEVELOPMENT_TEAM: 7PLLZ436SG
targets:
  SwipeFresh:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    sources: [SwipeFresh]
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: SwipeFresh
      INFOPLIST_FILE: SwipeFresh/Supporting/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: de.tum.cit.ase.university.ios23.fame
