name: SwipeFresh
targets:
  SwipeFresh:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    sources: [SwipeFresh]
    settings:
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_FILE: SwipeFresh/Supporting/Info.plist
      PRODUCT_NAME: SwipeFresh

