name: SwipeFresh
targets:
  HallOfFame:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    sources: [SwipeFresh]
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: SwipeFresh
      INFOPLIST_FILE: HallOfFame/Supporting/Info.plist

